### ISSUE TITLE
SCSS 404

### ISSUE THREAD

**Issue by komma-d** [FriendsOfShopware/FroshProductCompare#11]
hallo, beim kompilieren des scss bekommen wir zwei 404.
Diese Dateien werden in dem Plugin inkludiert.
@import 'scss/layout/_scroll-up';
@import "scss/variables";

<img width="577" alt="Bildschirmfoto 2020-11-13 um 16 52 23" src="https://user-images.githubusercontent.com/7209213/99092043-f2b05600-25d0-11eb-87d1-4398d651afb4.png">

**Comment by vienthuong** [comment]
Hi @komma-d 
Not sure why I'm not getting the error on my end, but as I checked the import in scss files, there're syntax error so I'll fixed it and released in the next version.
Thanks for reporting :).

**Comment by vienthuong** [comment]
@komma-d I fixed the issue, would you mind to check it on the latest version?

**Comment by vienthuong** [comment]
@komma-d 🤷🏼  can you give me your reproduce steps? Or did you try to rebuild the asset files/ clear cache/etc? if the issue's still not fixed you can contact me via skype in my github profile.

**Comment by komma-d** [comment]
the shop ist running on 6.3.2.1, prod Mode (theme:compile and cache:clear)
is it necassary to include this files? they are already included in the default theme
<img width="1738" alt="Bildschirmfoto 2020-11-16 um 11 34 22" src="https://user-images.githubusercontent.com/7209213/99243096-6edcb080-2800-11eb-8b96-bbb47013f592.png">
<img width="1185" alt="Bildschirmfoto 2020-11-16 um 11 34 29" src="https://user-images.githubusercontent.com/7209213/99243103-71d7a100-2800-11eb-9d38-592031bfc02c.png">

**Comment by vienthuong** [comment]
@komma-d hi there, i'm not sure why these files are necessary before, seems like there're some change in the platform :D But now I removed it and the plugin still works fine. Would you mind to check the latest tag again? Thank you :)

**Comment by komma-d** [comment]
sure, is there a update?

**Comment by vienthuong** [comment]
> sure, is there a update?

@komma-d I just removed the import scss files, hope it works for you 🤔

**Comment by komma-d** [comment]
perfect, thx
