### ISSUE TITLE
Posibility of activate or deactivate attributes 

### ISSUE THREAD

**Issue by marcoschulz92** [FriendsOfShopware/FroshProductCompare#15]
Hi, 

Is it possible to expand the plugin so that you can choose which attributes the plugin should display and compare? We have many attributes for a larger project through an ERP system, but we do not want to use them in the comparison.
Would this be possible and in what time context?

Thank you.

Greetz 
Marco
icue-medien

**Comment by vienthuong** [comment]
Hi Marco, I will have a look at this issue, we got a lot of request about this feature so we might implement it in the future when we have the resource, in the meantime, it'd be cool if you can give us some suggestion for what needs to be done in detail or even create a PR 😎 .

**Comment by vienthuong** [comment]
Hi @marcoschulz92 
I fix the issue and release v1.1.0, can you guys check out the latest version and let me know :)
