### ISSUE TITLE
Cross-Selling-Comparison not working for products with variants

### ISSUE THREAD

**Issue by spstiger** [FriendsOfShopware/FroshProductCompare#16]
I love this plugin. However the cross selling comparison does not seem to work with products with variants. It is a pity.

**Comment by vienthuong** [comment]
Hi @spstiger
Thank you for reaching out :) 
Yeah, that should be a critical bug, It'd be fixed in the next version :D

**Comment by spstiger** [comment]
great, thanks ;)

**Comment by pd-loewenstark-digital** [comment]
@vienthuong 
When can we expect the update? I also use this plugin and I cannot compare the two variants.

**Comment by vienthuong** [comment]
Hi @spstiger @pd-loewenstark-digital 
I fix the issue and release v1.1.0, can you guys check out the latest version and let me know :)
