### ISSUE TITLE
Modal Dialogue

### ISSUE THREAD

**Issue by grimclaw-draven** [FriendsOfShopware/FroshProductCompare#18]
### Question

Hi,

when we have more than 4 Articles to compare we have to Close the modal-dialog 4 Times.
Is this fixed in newer Versions. Our SW Version is v6.3.5.3

Thank You
Muhammed Tay

**Comment by vienthuong** [comment]
@grimclaw-draven Hi there, never heard of such an issue before, I did the test on 6.4 and cannot reproduce it. Might you double check it?
