### ISSUE TITLE
Hide Manufacturer (and Price) from List

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/FroshProductCompare#19]
It is already possible to select the compared fields, but the manufacturer (Hersteller) can not be hidden.

Would it be in scope to add this functionality?

Or should such a standard field be hidden more globally?

**Comment by vienthuong** [comment]
@amenk Yes, I'm thinking about the case by case like manufacturer, description, price...
Or does it make sense to you that I add an option to only show the field when they have different values? meant if the manufacturer of compare products are the same, it will be hidden.

**Comment by amenk** [comment]
Both would make sense
1. Option to hide fields with all-same values
2. Option to hide system values, like manufacturer, description, price 

So are you actually planing to implement this? :-)

**Comment by vienthuong** [comment]
I am not implementing it right now but I'd be pleased to do that when I got some free time since this is my pet project.
But an MR is always welcomed, just assign the issue to you if you think you need it urgently :)

**Comment by amenk** [comment]
We don't need it urgently, but in some weeks ... We will probably prioritize some other things, so we are happy if you implement it :-) Otherwise we sure will make a MR then.

**Comment by vienthuong** [comment]
I will make sure to inform you in this thread if I managed to complete it as soon as I can :)

**Comment by vienthuong** [comment]
Hi @amenk I know this take forever but better late than never right?

As I try to implement it, I decided to go with the option 2

`
2. Option to hide system values, like manufacturer, description, price
`

Hide fields that have the same value caused a little performance issue and I guess opt 2 can solve your problem already so I skip option 1 for now.

![image](https://user-images.githubusercontent.com/22548423/142477783-3765a408-c078-4ab6-9adf-0e7fdde6fe9c.png)

Could you try to update the plugin to 1.2.0 and give me feedback? Thanks

**Comment by vienthuong** [comment]
Feel free to re-open it if you have any issue

**Comment by amenk** [comment]
Thank you very much, we did not yet have time to test it, yet. But looking at the code, it looks just fine :-)
