### ISSUE TITLE
Could it be that the variant support for comparable cross sell was destroyed again in version 1.1.0??

### ISSUE THREAD

**Issue by spstiger** [FriendsOfShopware/FroshProductCompare#20]
### PHP Version

8

### Shopware Version

6.4.2.1 

### Actual behaviour

With version 1.1.0 I get an error on the product page if there are variants, when activating the plugin.
I tried to deinstall (option delete all data) and reinstall, but the problem persists. 

### Expected behaviour

Variant products with cross selling should show comparable products.

### Steps to Reproduce?

Use with cross selling products with variants.

**Comment by vienthuong** [comment]
Hi @spstiger 
I will have a look at this issue soon, thanks for reporting

**Comment by vienthuong** [comment]
Hi @spstiger 
I know this is super loooooong feedback but I fixes the issue, could you please update to 1.2.0 and check if your issue is fixed with the new version?

**Comment by spstiger** [comment]
Hi @vienthuong 
I checked it just now and it works with the new version ... thank you so much. I love the comparable cross sellings for technical products. Amazon style, it helps make an informed decision.
