### ISSUE TITLE
Use of ProductGateway instead of ProductGatewayInterface results in invalid argument error on __construct when ProductGateway is decorated

### ISSUE THREAD

**Issue by vanWittlaer** [FriendsOfShopware/FroshProductCompare#21]
### PHP Version

7.4

### Shopware Version

6.4.4.1

### Actual behaviour

Invalid argument error like "Argument 1 passed to Frosh\FroshProductCompare\Page\CompareProductPageLoader::__construct() must be an instance of Shopware\Core\Content\Product\Cart\ProductGateway, instance of VioCustomerPrice\Core\Content\Product\Cart\ProductGateway given, called in ..:" when ProductGateway is decorated

### Expected behaviour

ProductGateway can be decorated w/out causing invalid argument error

### Steps to Reproduce?

Install FroshProductCompare together with e.g. VioCustomerPrice plugin

**Comment by vienthuong** [comment]
Hi, thanks for your contribution, it's merged

**Comment by vanWittlaer** [comment]
Thx :smile:
