### ISSUE TITLE
found error when install the plugin and test to compare.

### ISSUE THREAD

**Issue by 4UForever** [FriendsOfShopware/FroshProductCompare#23]
### PHP Version

7.4

### Shopware Version

6.4.4.1

### Actual behaviour

![ภาพ](https://user-images.githubusercontent.com/13354566/136190934-256b2de9-630b-4969-8dd8-7ccbe59ef14f.png)
found this error while comparing products

### Expected behaviour

should not get the errors

### Steps to Reproduce?

select at least 2 products to compare and press the compare button

**Comment by vienthuong** [comment]
Hi @4UForever 
Sorry for the late response,
does the issue still happens? I guess it's a caching issue

**Comment by vienthuong** [comment]
Feel free to re-open it if you have any issue
