### ISSUE TITLE
capitalize

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshProductCompare#26]
### Question

What is the reason of the capitalizing?

`any property group` => `Any Property Group`
The content feels wrong. We should keep them as they are, shouldn't we?

https://github.com/FriendsOfShopware/FroshProductCompare/blob/23452a902c352439cbf36d62b6890a69b0e302e9/src/Resources/views/storefront/component/compare/section/specification.html.twig#L9

**Comment by vienthuong** [comment]
yes Its a good point, I simply capitalize it because it looks nicer with default properties but in production it should not be the case. Feel free to create a MR to fix otherwise I will fix it later.
Thanks @tinect
