### ISSUE TITLE
Display values of other variants in the compare table

### ISSUE THREAD

**Issue by neckerlein** [FriendsOfShopware/FroshProductCompare#32]
### Question

Is it possible to display property values of other variants in the compare table. (e.g. if i add a colour variant with green to the compare list -> display red and blue in the compare table as colour as well)

**Comment by tinect** [comment]
Hi @neckerlein 

This feature doesn't exist, and I don't see any globally need for such a feature while:
- it will make the Controller slower
- it will blow up the plugin with most not needed content
- it can and maybe will confuse any customer in most shops

@vienthuong what do you think?

**Comment by vienthuong** [comment]
Sorry for the late response.
I do agree with @tinect but I've written my own plugin that displays the property of other variants in the product list/detail as well. Currently, it doesn't work on the compare page but if you think it'll be a helpful solution for your case, I'd please to find a solution to make these plugins work together :) 

Please check it out and give me your opinion on that
https://github.com/Shape-and-Shift/shopware-variant-switch/
