### ISSUE TITLE
Show only differences by comparing

### ISSUE THREAD

**Issue by ostermueller** [FriendsOfShopware/FroshProductCompare#33]
### Please describe the feature you would like to see implemented.

It should be possible to display only differences when comparing. Same attributes should be hidden.

**Comment by vienthuong** [comment]
Hi @ostermueller 
Good idea but currently I don't have much time to implement it, feel free to contribute the feature or I will dive into it later :)

**Comment by ostermueller** [comment]
Maybe something like https://jsfiddle.net/ut82mekr/1/ solution

**Comment by vienthuong** [comment]
@ostermueller nice idea, I added your implementation with some tweaks in the new release (2.0.0)
