### ISSUE TITLE
Double "compare button" for configurable products since 6.4.13

### ISSUE THREAD

**Issue by constancyGmbH** [FriendsOfShopware/FroshProductCompare#34]
### Shopware Version

6.4.13

### Actual behaviour

As you can see, with configurable products the Button for compare is doubled since the update to Shopware 6.4.13

You can check it online on our store: https://www.niesky-moebel-shop.de

![grafik](https://user-images.githubusercontent.com/5858874/183915139-56193fac-d107-4359-8a11-c0ba3a1b7a3d.png)

### Expected behaviour

Show Button only once

### Steps to Reproduce?

We just did the Update to Shopware 6.4.13

**Comment by constancyGmbH** [comment]
Since I can't find the Problem, I qickfixed it with a css class
```
.card .card-body .product-info .compare-button:nth-child(2){
	display: none;
}
```

But this is no final solution 😔

**Comment by vienthuong** [comment]
Hi @constancyGmbH, 
Could you try to describe the bug more specific?
Maybe your theme or some other plugins make the bug happend, I'm currently on 6.4.13 but the button only displays once

![image](https://user-images.githubusercontent.com/22548423/184920218-1370add7-d70f-493c-833d-ab0178a4ce35.png)

**Comment by shyim** [comment]
I will close this as inactive
