### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Mark01000** [FriendsOfShopware/FroshProductCompare#38]
### Please describe the feature you would like to see implemented.

HI,
great Plugin for free.

I would be happy if you could install a function that allows you to select the category in which the comparison should be possible. I would like to offer the comparison only in selected categories.

Thank you 
Mark

**Comment by vienthuong** [comment]
Hi currently we are releasing 2.0.0 with a few new features, but your proposal is not yet implemented. It's because we don't think it will be largely used for most use cases so we don't push much effort for this. Feel free to create a PR for this MR or if it gathers much interest we will consider adding it in the next version.

**Comment by Mark01000** [comment]
Okay. Would it then alternatively possible to include a switch whether the item can be compared? Just like cross-selling ("Compare" switch).

**Comment by vienthuong** [comment]
That could be easily implemented by adding a boolean custom field for the product (comparable by default). I'd do it in the next release :)

**Comment by Mark01000** [comment]
that sounds good.
if the switch is disabled, there is also no button in the article and under the shopping cart button in the category listing? 
That would be perfect for my purposes.

**Comment by tinect** [comment]
From the users' perspective, this feels confusing. For the moment, it feels wrong to add that function globally, what we need to maintain.

But I like to understand it.
What is your business to have such needs? 🤔

**Comment by tinect** [comment]
Closed due to inactivity.
