### ISSUE TITLE
Compatibility for Shopware 6.5

### ISSUE THREAD

**Issue by huelsmc** [FriendsOfShopware/FroshProductCompare#43]
### Please describe the feature you would like to see implemented.

We'd like to know if there are any plans to make this plugin compatible with Shopware 6.5 and if so if there is already some rough timeline for it?

We use it in multiple shops and are currently evaluating updating these shops starting in June.

**Comment by vienthuong** [comment]
Hi, 
Sure, I will make it compatible with 6.5 this weekend since I will have some free time :)

**Comment by M4MEET** [comment]
i want toggle on/off option to disable compare button  for product slider in plugin configuration
