### ISSUE TITLE
Non-Multilingual Custom Fields

### ISSUE THREAD

**Issue by pfeitim** [FriendsOfShopware/FroshProductCompare#48]
### PHP Version

8.2.7

### Shopware Version

6.5.3.3

### Actual behaviour

Custom fields that are only available in the shop's main language are not displayed in the other languages. If you compare products and change the language in the shop to a secondary language, the values of the custom field become empty ("-"), even if the custom field is to be used for all shop languages as per shopware field-set settings. 

### Expected behaviour

If the checkbox "Maintain in all administration languages" is deactivated in the shopware custom field settings (set-information), the main language counts as a global custom field for all languages. This behaviour should also be reproduced in the output in the product comparison. 

### Steps to Reproduce?

0. You need to have a multilingual shopware shop

1. Create a custom field set for products, leave "Maintain in all administration languages" deactivated. 
2. Create a custom field (text) in this set. 
3. Create a product and fill the custom field in the main language of your shop
5. Add the product to product comparison in the frontend (main shop language)
6. Switch to another language in your shop. The custom field content in comparison is gone/empty.

You can simulate the problem in our live shop with this article and the additional field "Norm/Certification":
https://fortdress-group.com/frische-jacke-taiga/fbj12

<img width="1065" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/ff152809-f05a-4f30-8fdd-a38feda8ecf9">

<img width="1407" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/288af9d2-acc3-4a0e-9d35-8ee54cc4f7ad">

<img width="1339" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/5f6773c1-1a62-4b8e-89f9-47e23d8e7c44">

**Comment by tinect** [comment]
Hey @pfeitim,
FYI: There is no setting `Maintain in all administration languages`.
In English, it is called `Manage labels in all administration languages`. I agree, the description in German is misleading.
But you see, this setting has nothing to with customFields.

But, the problem is simple to fix: https://github.com/FriendsOfShopware/FroshProductCompare/pull/55
