### ISSUE TITLE
Product ratings not showing correctly for product variants

### ISSUE THREAD

**Issue by pfeitim** [FriendsOfShopware/FroshProductCompare#49]
### PHP Version

8.2.7

### Shopware Version

6.5.3.3

### Actual behaviour

If you add some product variants to the product comparison and their main product items have ratings, the stars of the ratings are displayed orange-coloured in the comparison, but the subtitle remains "0 ratings". 

### Expected behaviour

It should show the correct number of ratings for each variant when comparing the variant - even if the rating is for the main product and not for the variant itself.

Optional: It would be nice if there was a setting to always compare the main product.

### Steps to Reproduce?

1. Create a shopware product with min. 2 variants 
2. Create a product rating, publish product rating
3. Add a variant of the according product to the product comparison. 

You can take a look at our shop where the problem occurs – Use this product and add it to the comparison: 
https://fortdress-group.com/frische-jacke-taiga/fbj12

<img width="1395" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/8e9d7e06-6399-464a-8ded-c5816825a2bb">

**Comment by tinect** [comment]
I understand this confusing behaviour.
The stars are based on the entire product, including variants, which is shopware default.

The reviews are loaded besides default.
The default from shopware would be to have the count of all reviews also like happening in detail.
I think this should be the goal of this.

Regarding your idea of having just the reviews of this variant could result in confused customers, while the product detail would show different review status.

That is the reason, I think this should be the goal:
- get the same review-count as in product detail

What do you think @vienthuong ?

**Comment by pfeitim** [comment]
@tinect That's absolutely what i wanted to mention: get the same review-count as in the main product – no need for ratings per variant...

**Comment by vienthuong** [comment]
@tinect @pfeitim Sorry I missed this thread,
So conclusion: we should show the total number of reviews of each variant in the comparison?
Sounds completely valid to me 👍🏽

**Comment by tinect** [comment]
@vienthuong no, we mean: just the same number as in detail page, which is over all variants. 😁

**Comment by vienthuong** [comment]
ah yes, that shoulds good at well 👍🏽
