### ISSUE TITLE
Version 2.0.0 Storefront JS compiled with old offcanvas-content-container class

### ISSUE THREAD

**Issue by lacknere** [FriendsOfShopware/FroshProductCompare#60]
### PHP Version

8.1

### Shopware Version

6.5.6.0

### Actual behaviour

When opening any offcanvas, the loader symbol is misplaced because it is wrapped with the old container class "offcanvas-content-container" instead of the new "offcanvas-body" class. It seems like the storefront javascript for version 2.0.0 was compiled with Shopware 6.4 because the compiled js file contains the old "offcanvas-content-container" class.

### Expected behaviour

Centered loader symbol in any offcanvas instance using "offcanvas-body" wrapper class.

### Steps to Reproduce?

Install and activate the compare plugin > open any offcanvas instance (compare, cart, etc.)

**Comment by lacknere** [comment]
Actually the class was just changed with version 6.5.4.0 https://github.com/shopware/shopware/commit/37cb3d6b62233088438001a016a1e51e53871a7c
A recompilation of the admin scripts with Shopware 6.5.4.0 or newer would fix this issue.

**Comment by tinect** [comment]
It should be fixed with 2.0.1
