### ISSUE TITLE
Make Product Comparison available only for a certain logged in customer group

### ISSUE THREAD

**Issue by nikkoch** [FriendsOfShopware/FroshProductCompare#62]
### Please describe the feature you would like to see implemented.

Hello and thank you for the great solution!

Would it be possible to make Product Comparison available only for a certain logged in customer group? 
What are the options to make this work?

**Comment by nikkoch** [comment]
Is it maybe possible to hide UI elements just for non logged in users?

**Comment by vienthuong** [comment]
@nikkoch it's certainly doable :) you just need to check if the context.customer exists

```twig
{% if context.customer and context.customer.guest %}
    // UI components         
{% endif %}
```
