### ISSUE TITLE
Comparison shows text "0 ratings" for item with rating

### ISSUE THREAD

**Issue by pfeitim** [FriendsOfShopware/FroshProductCompare#66]
### PHP Version

8.2.13

### Shopware Version

6.5.7.3

### Plugin Version

2.0.0 (latest github)

### Actual behaviour

When a product has a rating, the comparison shows the filled stars, but the text "0 ratings"

<img width="399" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/bb2d2d3e-d4ca-4985-8162-2503d6bfdce4">

Product: 
<img width="450" alt="image" src="https://github.com/FriendsOfShopware/FroshProductCompare/assets/16204467/58157d8e-c1b3-4090-90df-7f8da7de883d">

### Expected behaviour

It needs to show the correct review amount

### Steps to Reproduce?

You can test it here, just add this item to comprison, which has 1 rating: 
https://fortdress-group.com/tiefkuehl-handschuh-falcon/fg790-2xl

**Comment by tinect** [comment]
Hey @pfeitim,
this seems to be part of https://github.com/FriendsOfShopware/FroshProductCompare/issues/49 ?

The fix in https://github.com/FriendsOfShopware/FroshProductCompare/commit/cb109215b7642ea80bb36f1fd2eaa4a3013e6be4 has not been released yet. @vienthuong should we bundle a new release (https://github.com/FriendsOfShopware/FroshProductCompare/compare/2.0.0...main)? :-)

**Comment by tinect** [comment]
@pfeitim
I increased the minimum version for v2 to 6.5.8. While there was no reaction I'd overtake this and give you a dedicated release for `>6.5.8 <6.6`. Would you need it furthermore?
