### ISSUE TITLE
Product Comparison won't work

### ISSUE THREAD

**Issue by Tfc538** [FriendsOfShopware/FroshProductCompare#68]
### PHP Version

8.2.15

### Shopware Version

6.5.8.2

### Plugin Version

2.0.0

### Actual behaviour

The product selection functionality doesn't work. Whenever we added products to the product comparison and then click the button to start the comparison nothing happens.

### Expected behaviour

The product comparison feature should respond appropriately, allowing to start a comparison between them.

### Steps to Reproduce?

1. Add products to the product comparison
2. Click the button to start the comparison
3. Observe that nothing changes

**Comment by ostermueller** [comment]
any plan to fix the issue?

**Comment by itmaniax** [comment]
Also facing this issue with the latest version 2.0.0.
It works with shopware 6.5.7.4 but not with 6.5.8.*

**Comment by spstiger** [comment]
got the same issue

**Comment by czimmer-kiag** [comment]
Any updates?

We have the same issue under SW 6.5.8.7

**Comment by Tfc538** [comment]
Nope didn't fix yet

**Comment by avhulst** [comment]
Same problem with 6.5.8.11, but i found it. `frosh-product-compare.js` is not a 6.5.8.x compatible build. Here my compatible build: https://github.com/avhulst/FroshProductCompare/blob/feature/fix-6.5.8.11/src/Resources/app/storefront/dist/storefront/js/frosh-product-compare.js
I think Frosh has to release a 2.0.1 ;-)

**Comment by ostermueller** [comment]
@avhulst avhulst thanks a lot! you just saved me a lot of time - works fine :)

**Comment by M4MEET** [comment]
is the release with fix  coming out soon?

**Comment by tinect** [comment]
Let me support @vienthuong. I just tagged a new release for v2.
