### ISSUE TITLE
Produkte können aus der Sidebar nicht gelöscht werden

### ISSUE THREAD

**Issue by komma-d** [FriendsOfShopware/FroshProductCompare#9]
— counter Badge ändert sich auch nicht

**Comment by vienthuong** [comment]
Hi @komma-d ,  thanks for creating the issue, can you give me some more information related to the bug? I have tried the latest plugin's version on SW6.3 and the counter works fine.

http://shopware.thuong.lv/

**Comment by komma-d** [comment]
hi @vienthuong , thanks für the fast replay – it seems it was a issue on our side. 
It is not possible to use a Icon inside the compare-button, because the script replaces the inner html on click so the icon got removed. Can you extend the options with  addedText: false or something? thanks

**Comment by vienthuong** [comment]
got your point, I will try to fix it soon but feel free to create a MR 👍🏼

**Comment by vienthuong** [comment]
@komma-d Hi, sorry for the late response.

I add a config in plugin config to allow toggle the Add To Compare button without using text. It will look like this.

![image](https://user-images.githubusercontent.com/22548423/96372942-a6215880-1193-11eb-8de2-cf46e9b07b61.png)

![image](https://user-images.githubusercontent.com/22548423/96372927-9570e280-1193-11eb-931f-8e247a3b6d4d.png)

You can try it in the latest plugin's version v1.0.5.
